runtime: python38
entrypoint: gunicorn -b :$PORT main:app --timeout 300 --workers 5 --threads 30
service: dev

# https://cloud.google.com/appengine/docs/standard#instance_classes
instance_class: B4_1G

# https://cloud.google.com/appengine/docs/standard/python3/config/appref#scaling_elements
# Automatic scaling: task processing must finish in 10 minutes.
# For manual and basic cloud task requests can run up to 24 hours.
basic_scaling:
  max_instances: 3

handlers:
- url: /.*
  secure: always
  script: auto




